config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  get 'products/index'
  get '/product/:id', to: 'products#show', as: 'product'
  get 'products/index'

  get '/shopping_carts/add/:id', to: 'shopping_carts#add', as: 'shopping_carts_add'
  get 'shopping_carts/clear'

  post 'orders/create', to: 'orders#create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
  after_save :update_product_counters

  belongs_to :product

  enum kind: [:bought, :viewed, :carted]

  # не позволять создавать одинаковые события
  validates :product_id, uniqueness: { scope: [:kind, :group] }


  private
  
    def update_product_counters
      product = Product.find(self.product_id)

      # тип события подставляется сам
      event_count = Event.where(product: product).count

      product.update_attribute("#{self.kind}_count", event_count)
    end
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :events


  # отсортировать товары по количеству покупок, просмотров и добавлений в корзину
  scope :ordered, -> {
    ordered_by(:bought).
    ordered_by(:viewed).
    ordered_by(:carted)
  }

  # отсортировать товары по количеству определенных событий
  scope :ordered_by, ->(event_kind) {
    order("`#{event_kind}_count` DESC")
  }


  # товары, что рекомендуются с данным товаром
  def recommended_by(event_kind)
    Product.
    joins(:events).
    where.not(id: self.id).
    where(events: { kind: Event.kinds[event_kind] }).
    where("
      `events`.`group` IN (
        SELECT DISTINCT
          `group`
        FROM `events`
        WHERE `events`.`product_id` = #{self.id} AND
          `events`.`kind` = #{Event.kinds[event_kind]}
      )
    ").
    ordered_by(event_kind)
  end


  # товары, что покупались с данным
  def bought_with
    recommended_by :bought
  end

  # товары, что просматривались с данным
  def viewed_with
    recommended_by :viewed
  end

  # товары, что попадали в корзину с данным
  def carted_with
    recommended_by :carted
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  acts_as_shopping_cart

  def count
  	shopping_cart_items.length
  end
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
  acts_as_shopping_cart_item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :extract_shopping_cart
  before_filter :extract_order

  private
  def extract_shopping_cart
    shopping_cart_id = session[:shopping_cart_id]
    @shopping_cart = session[:shopping_cart_id] ? ShoppingCart.find(shopping_cart_id) : ShoppingCart.create
    session[:shopping_cart_id] = @shopping_cart.id
  end

  def extract_order
    @order = Order.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    # создать новый заказ
    @order = Order.new order_params
    @order.save

    # создать событие покупки для каждого товара в заказе
    @shopping_cart.shopping_cart_items.each do |item|
      Event.bought.create(
        group: @order.id,
        product_id: item.item_id
      )
    end
    
    # очистить корзину
    @shopping_cart.clear
    
    redirect_to :back, notice: "Ваше замовлення прийнято. Дякуємо за покупку!"
  end

  private
    def order_params
      params.require(:order).permit(:client_name, :client_phone)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.ordered
  end

  def show
    @product = Product.find params[:id]
    
    Event.viewed.create(
      group: request.env['rack.session'].id,
      product_id: @product.id
    )
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  def add
    @product = Product.find params[:id]
    @shopping_cart.add @product, @product.price

    Event.carted.create(
      group: @shopping_cart.id,
      product_id: @product.id
    )

    redirect_to :back
  end

  def clear
    @shopping_cart.clear
    session[:shopping_cart_id] = nil
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/layouts/application.html.haml
!!!
%html(lang="en")
  %head
  %meta(charset="utf-8")/
  %meta(content="width=device-width, initial-scale=1.0" name="viewport")/
  %title= content_for?(:title) ? yield(:title) : "Bender shop by Delfit team"
  = stylesheet_link_tag    "application"
  = javascript_include_tag "vendor/modernizr"
  = csrf_meta_tags
  %body
    %nav.top-bar(data-topbar="" role="navigation")
      %ul.title-area
        %li.name
          %h1
            = link_to(root_path) do
              Bender shop
        / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
        %li.toggle-topbar.menu-icon
          %a(href="#")
            %span Menu
      %section.top-bar-section
        / Right Nav Section
        %a.button.right.cart(href="#" data-action="open-cart")
          = "Товарів: #{@shopping_cart.count} на сумму #{@shopping_cart.total} грн."
        .medium.cart(class="f-dropdown" data-container="cart")
          = render 'cart'
    - flash.each do |name, msg|
      .alert-box.info.radius{"data-alert" => ""}
        = msg
        %a.close{:href => "#"} &times;
    %br
    = yield
    .panel.footer
      .text-center
        .label.alert
          Delfit 2014
    = javascript_include_tag "application"

app/views/products/_cart.html.haml
- if @shopping_cart.shopping_cart_items.length > 0
  - @shopping_cart.shopping_cart_items.each do |item|
    .row.item
      .large-12.columns
        = render 'cart_item', {item: item}
  .row
    .large-12.columns
      = form_for @order, url:orders_create_path do |f|
        .row
          .large-6.columns
            = f.text_field :client_name, placeholder:"Ваше Ім’я *", required:""
          .large-6.columns
            = f.text_field :client_phone, placeholder:"Ваш номер телефону *", data:{mask:"(999)9999999"}, required:""
        %hr
        .row
          .large-6.columns
            %a.button.center.alert.left.tiny{href:"#{shopping_carts_clear_path}"}
              Очистити кошик
          .large-6.columns
            %button.button.center.success.right.tiny(type="submit")
              Оформити замовлення
- else
  .row
    .large-12.columns
      %p
        Кошик пустий. Додайте будь-ласка товар, який ви хочете придбати :)

app/views/products/_cart_item.html.haml
.row
  .large-2.columns
    = link_to(product_path(item.item)) do
      %img(src="#{item.item.image_url}")
  .large-10.columns
    %p
      %b
        = link_to(product_path(item.item)) do
          = item.item.title
    %p
      %i
        = "#{item.quantity} x #{item.price} = #{item.quantity * item.price} грн."

app/views/products/_group.html.haml
- if products.length > 0
  %h5.subheader
    = title
  %hr
  %ul.small-block-grid-2
    - products.sample(4).each do |product|
      %li
        = render 'group_item', { product: product }

app/views/products/_group_item.html.haml
= link_to(product_path(product), { class: 'th', title: product.title }) do
  %img(src="#{product.image_url}")

app/views/products/_product.html.haml
.row
  .large-12.columns
    .row
      .large-12.columns
        %h6.subheader
          = product.title
        %img(src="#{product.image_url}")
    %hr
    .row
      .large-6.columns
        %span.alert.label
          = "#{product.price} грн."
      .large-6.columns
        %a.right.tiny.button.buy(href="#{shopping_carts_add_path(product)}")
          Купити

app/views/products/index.html.haml
%div.row
  %div.large-12.columns
    %ul.small-block-grid-4
      - @products.each do |product|
        = link_to(product_path(product)) do
          %li.product(title="#{product.title}")
            = render 'product', { product: product }

app/views/products/show.html.haml
.row
  .large-3.columns
    .row.product-image
      .large-12.columns
        %img(src="#{@product.image_url}")
    .row
      .large-12.columns
        .row
          .large-4.columns.button.tiny(title="Переглядів: #{@product.viewed_count}")
            = @product.viewed_count
          .large-4.columns.button.tiny.alert(title="Куплено: #{@product.bought_count}")
            = @product.bought_count
          .large-4.columns.button.tiny(title="Замовлено: #{@product.carted_count}")
            = @product.carted_count
  .large-9.columns         
    %h1.subheader
      = @product.title
    .row
      .large-6.columns
        .price
          = "#{@product.price} грн."
      .large-6.columns
        %a.right.button.buy(href="#{shopping_carts_add_path(@product)}")
          Купити
    %hr
    %p
      = @product.description
%br
.row
  .large-12.columns
    %ul.small-block-grid-3
      %li
        = render 'group', { title: 'З цим товаром також купують', products: @product.bought_with.limit(10) }
      %li
        = render 'group', { title: 'З цим товаром також переглядають', products: @product.viewed_with.limit(10) }
      %li
        = render 'group', { title: 'З цим товаром також замовляють', products: @product.carted_with.limit(10) }